---
- name: Secure Ubuntu18
  hosts: all
  become: yes
  tasks:
    - name: Update apt packs
      shell: "apt update"

    - name: Stop SSH
      shell: "systemctl disable ssh && systemctl stop ssh"
      ignore_errors: yes

    - name: Stop http
      shell: "systemctl disable httpd && systemctl stop httpd"
      ignore_errors: yes

    - name: Install UFW
      shell: "apt install ufw -y"

    - name: Start UFW
      shell: "ufw enable"

    - name: Deny ssh
      shell: "ufw deny ssh"

    - name: Deny http
      shell: "ufw deny http"

    

    

