---
- name: Secure Fedora
  hosts: all
  become: yes
  tasks:
    - name: Stop SSH
      shell: "systemctl disable sshd && systemctl stop sshd"

    - name: Start firewalld
      shell: "systemctl enable firewalld && systemctl start firewalld"

    - name: Allow POP3
      shell: "firewall-cmd --permanent --add-port=110/tcp"
    
    - name: Allow IMAP
      shell: "firewall-cmd --permanent --add-port=143/tcp"

    - name: Allow SMTP
      shell: "firewall-cmd --permanent --add-port=25/tcp"

    - name: Allow mySQL
      shell: "firewall-cmd --permanent --add-port=3306/tcp"
    
    - name: Deny HTTP
      shell: "firewall-cmd --permanent --remove-port=80/tcp"
    
    - name: Deny SSH
      shell: "firewall-cmd --permanent --remove-port=22/tcp"

    - name: Apply firewalld changes
      shell: "firewall-cmd --reload"

    - name: Turn off HTTP
      shell: "systemctl disable httpd && systemctl stop httpd"

    
  