---
- name: Secure Fedora
  hosts: all
  become: yes
  tasks:
    - name: Stop SSH
      shell: "systemctl disable sshd && systemctl stop sshd"
  
    - name: Remove users from fedora system
      user:
        name: "{{ item }}"
        state: absent
      loop:
        - abwise
        - administrator
        - brwake
        - cdsims

    - name: Install UFW
      shell: "yum install -y ufw"

    - name: Enable UFW
      shell: "systemctl enable ufw"

    - name: Start UFW
      shell: "systemctl start ufw"
    
    - name: Allow imap
      shell: "ufw allow imap" 
    
    - name: Allow smtp
      shell: "ufw allow smtp"

    - name: Allow pop3
      shell: "ufw allow pop3"
    
    - name: Apply ufw changes
      shell: "ufw reload"

    - name: Check ufw status
      shell: "ufw status verbose"