---
- name: Secure CentOS7
  hosts: all
  become: yes
  tasks:
    - name: Update yum repo
      yum:
        name: "*"
        state: latest

    - name: Stop SSH
      ansible.builtin.shell: "systemctl disable sshd && systemctl stop sshd"

    - name: Start firewalld
      shell: "systemctl enable firewalld && systemctl start firewalld"

    - name: Allow 80
      shell: "firewall-cmd --permanent --add-port=80/tcp"
    
    - name: Deny SSH
      shell: "firewall-cmd --permanent --remove-port=22/tcp"

    - name: Apply firewalld changes
      shell: "firewall-cmd --reload"

    

    

