---
- name: Secure Fedora
  hosts: all
  become: yes
  tasks:
    - name: Stop SSH
      ansible.builtin.shell: "systemctl disable sshd && systemctl stop sshd"

    - name: Get SSH status
      ansible.builtin.shell: "systemctl status sshd"
      register: ssd_status
    
    - name: Display SSH status after stopping
      debug:
        msg: "{{ ssd_status.stdout }}"
  
    - name: Remove users from fedora system
      user:
        name: "{{ item }}"
        state: absent
      loop:
        - abwise
        - administrator
        - brwake
        - cdsims

    - name: Print Hello World
      debug:
        msg: "Hello World"